; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _main

    .text

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 4 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 100
    STA -2,FP
    LDI 200
    STA -4,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
