; NEANDER-X 16-bit Assembly
; Generated by LCC (16-bit target)

; Runtime variables (page zero for fast access)
    .org 0x0000
_tmp:    .word 0     ; General purpose 16-bit temp
_tmp2:   .word 0     ; Second 16-bit temp for binary ops
_tmp_lo: .byte 0     ; 16-bit temp low byte
_tmp_hi: .byte 0     ; 16-bit temp high byte
_t2_lo:  .byte 0     ; Second 16-bit temp low
_t2_hi:  .byte 0     ; Second 16-bit temp high
_t3_lo:  .byte 0     ; Third 16-bit temp low (for 32-bit ops)
_t3_hi:  .byte 0     ; Third 16-bit temp high
_t4_lo:  .byte 0     ; Fourth 16-bit temp low (for 32-bit ops)
_t4_hi:  .byte 0     ; Fourth 16-bit temp high
_zero:   .byte 0     ; Constant zero (for clearing carry)

; Code section starts at 0x0100 (page 0 reserved for stack)
    .org 0x0100

    .global _add

    .text

; Function: add
_add:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4
    PUSH
    LDA 4+1
    LDA 6
    PUSH
    LDA 6+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    TAY
    POP
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _sub

; Function: sub
_sub:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4
    PUSH
    LDA 4+1
    LDA 6
    PUSH
    LDA 6+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    LDI 0
    ADD _zero
    LDA _t2_lo
    SUB _tmp_lo
    PUSH
    LDA _t2_hi
    SBC _tmp_hi
    TAY
    POP
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 12 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI lo(50)
    PUSH
    LDI hi(50)
    LDI lo(30)
    PUSH
    LDI hi(30)
    PUSH
    POP
    PUSH
    PUSH
    PUSH
    POP
    PUSH
    PUSH
    CALL _add
    PUSH
    TYA
    STA -6+1
    POP
    STA -6
    PUSH
    POP
    PUSH
    PUSH
    PUSH
    POP
    PUSH
    PUSH
    CALL _sub
    PUSH
    TYA
    STA -8+1
    POP
    STA -8
    LDA -6
    PUSH
    LDA -6+1
    LDA -8
    PUSH
    LDA -8+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    TAY
    POP
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
