; NEANDER-X 16-bit Assembly
; Generated by LCC (16-bit target)

; Runtime variables (page zero for fast access)
    .org 0x0000
_tmp:    .word 0     ; General purpose 16-bit temp
_tmp2:   .word 0     ; Second 16-bit temp for binary ops
_tmp_lo: .byte 0     ; 16-bit temp low byte
_tmp_hi: .byte 0     ; 16-bit temp high byte
_t2_lo:  .byte 0     ; Second 16-bit temp low
_t2_hi:  .byte 0     ; Second 16-bit temp high
_t3_lo:  .byte 0     ; Third 16-bit temp low (for 32-bit ops)
_t3_hi:  .byte 0     ; Third 16-bit temp high
_t4_lo:  .byte 0     ; Fourth 16-bit temp low (for 32-bit ops)
_t4_hi:  .byte 0     ; Fourth 16-bit temp high
_zero:   .byte 0     ; Constant zero (for clearing carry)

; Code section starts at 0x0100 (page 0 reserved for stack)
    .org 0x0100

    .global _increment

    .text

; Function: increment
_increment:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDA _counter
    PUSH
    LDA _counter+1
    LDA _step
    PUSH
    LDA _step+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    STA _counter+1
    POP
    STA _counter
    LDA _counter
    PUSH
    LDA _counter+1
    TAY
    POP
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    LDI lo(0)
    PUSH
    LDI hi(0)
    STA _counter+1
    POP
    STA _counter
    LDI lo(5)
    PUSH
    LDI hi(5)
    STA _step+1
    POP
    STA _step
    CALL _increment
    PUSH
    TYA
    CALL _increment
    PUSH
    TYA
    CALL _increment
    PUSH
    TYA
    LDA _counter
    PUSH
    LDA _counter+1
    TAY
    POP
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _step
_step:
    .space 2
    .global _counter
_counter:
    .space 2

; End of program
    HLT
