; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _increment

    .text

; Function: increment
_increment:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    STA -2,FP
    LDA _counter
    STA _tmp
    LDA _step
    ADD _tmp
    STA _counter
    LDA _counter
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    LDI 0
    STA _counter
    LDI 5
    STA _step
    CALL _increment
    CALL _increment
    CALL _increment
    LDA _counter
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _step
_step:
    .space 2
    .global _counter
_counter:
    .space 2

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
