; NEANDER-X 16-bit Assembly
; Generated by LCC (16-bit target)

; Runtime variables (page zero for fast access)
    .org 0x0000
_tmp:    .word 0     ; General purpose 16-bit temp
_tmp2:   .word 0     ; Second 16-bit temp for binary ops
_tmp_lo: .byte 0     ; 16-bit temp low byte
_tmp_hi: .byte 0     ; 16-bit temp high byte
_t2_lo:  .byte 0     ; Second 16-bit temp low
_t2_hi:  .byte 0     ; Second 16-bit temp high
_t3_lo:  .byte 0     ; Third 16-bit temp low (for 32-bit ops)
_t3_hi:  .byte 0     ; Third 16-bit temp high
_t4_lo:  .byte 0     ; Fourth 16-bit temp low (for 32-bit ops)
_t4_hi:  .byte 0     ; Fourth 16-bit temp high
_zero:   .byte 0     ; Constant zero (for clearing carry)

; Code section starts at 0x0100 (page 0 reserved for stack)
    .org 0x0100

    .global _sum_array

    .text

; Function: sum_array
_sum_array:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI lo(0)
    PUSH
    LDI hi(0)
    LDA _data
    PUSH
    LDA _data+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    LDA _data+2
    PUSH
    LDA _data+2+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    LDA _data+4
    PUSH
    LDA _data+4+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    LDA _data+6
    PUSH
    LDA _data+6+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    LDA _data+8
    PUSH
    LDA _data+8+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    TAY
    POP
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI lo(10)
    PUSH
    LDI hi(10)
    STA _data+1
    POP
    STA _data
    LDI lo(20)
    PUSH
    LDI hi(20)
    STA _data+2+1
    POP
    STA _data+2
    LDI lo(30)
    PUSH
    LDI hi(30)
    STA _data+4+1
    POP
    STA _data+4
    LDI lo(40)
    PUSH
    LDI hi(40)
    STA _data+6+1
    POP
    STA _data+6
    LDI lo(50)
    PUSH
    LDI hi(50)
    STA _data+8+1
    POP
    STA _data+8
    CALL _sum_array
    PUSH
    TYA
    TAY
    POP
_L6:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _data
_data:
    .space 10

; End of program
    HLT
