; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _sum_array

    .text

; Function: sum_array
_sum_array:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA _data
    ADD _tmp
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA _data+2
    ADD _tmp
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA _data+4
    ADD _tmp
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA _data+6
    ADD _tmp
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA _data+8
    ADD _tmp
    STA -2,FP
    LDA -2,FP
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 10
    STA _data
    LDI 20
    STA _data+2
    LDI 30
    STA _data+4
    LDI 40
    STA _data+6
    LDI 50
    STA _data+8
    CALL _sum_array
    STA -2,FP
; ret - value in AC
_L6:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _data
_data:
    .space 10

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
