; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _factorial

    .text

; Function: factorial
_factorial:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 6 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 1
    STA -4,FP
    LDI 1
    STA -2,FP
    JMP _L3
_L2:
    LDA -2,FP
    TAX
    LDA -4,FP
    MUL
    STA -4,FP
    LDA -2,FP
    STA _tmp
    LDI 1
    ADD _tmp
    STA -2,FP
_L3:
    LDA -2,FP
    STA _tmp2
    LDA 4,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JLE _L2
    LDA -4,FP
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 5
    PUSH
    CALL _factorial
    STA -2,FP
; ret - value in AC
_L5:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
