; NEANDER-X 16-bit Assembly
; Generated by LCC (16-bit target)

; Runtime variables (page zero for fast access)
    .org 0x0000
_tmp:    .word 0     ; General purpose 16-bit temp
_tmp2:   .word 0     ; Second 16-bit temp for binary ops
_tmp_lo: .byte 0     ; 16-bit temp low byte
_tmp_hi: .byte 0     ; 16-bit temp high byte
_t2_lo:  .byte 0     ; Second 16-bit temp low
_t2_hi:  .byte 0     ; Second 16-bit temp high
_t3_lo:  .byte 0     ; Third 16-bit temp low (for 32-bit ops)
_t3_hi:  .byte 0     ; Third 16-bit temp high
_t4_lo:  .byte 0     ; Fourth 16-bit temp low (for 32-bit ops)
_t4_hi:  .byte 0     ; Fourth 16-bit temp high
_zero:   .byte 0     ; Constant zero (for clearing carry)

; Code section starts at 0x0100 (page 0 reserved for stack)
    .org 0x0100

    .global _factorial

    .text

; Function: factorial
_factorial:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 6 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI lo(1)
    PUSH
    LDI hi(1)
    LDI lo(1)
    PUSH
    LDI hi(1)
    JMP _L3
_L2:
    TAX
    POP
    MUL
    PUSH
    TYA
    LDI lo(1)
    PUSH
    LDI hi(1)
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
_L3:
    LDA 4
    PUSH
    LDA 4+1
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    STA _t2_lo
    LDA _t2_hi
    CMP _tmp_hi
    JN _L2
    JNZ _nle__L2
    LDA _t2_lo
    CMP _tmp_lo
    JBE _L2
_nle__L2:
    TAY
    POP
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI lo(5)
    PUSH
    LDI hi(5)
    PUSH
    POP
    PUSH
    PUSH
    CALL _factorial
    PUSH
    TYA
    TAY
    POP
_L5:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
