; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Memory layout:
; 0x0000-0x002F: Runtime variables (below stack area)
; 0x0030-0x00FF: Stack (SP starts at 0x00FF, grows down)
; 0x0100+: Code

; Jump to startup code at 0x0100
    .org 0x0000
    JMP _start

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values
_vreg0:   .word 0     ; VREG spill slot 0
_vreg1:   .word 0     ; VREG spill slot 1
_vreg2:   .word 0     ; VREG spill slot 2
_vreg3:   .word 0     ; VREG spill slot 3
_vreg4:   .word 0     ; VREG spill slot 4
_vreg5:   .word 0     ; VREG spill slot 5
_vreg6:   .word 0     ; VREG spill slot 6
_vreg7:   .word 0     ; VREG spill slot 7
_vreg8:   .word 0     ; VREG spill slot 8
_vreg9:   .word 0     ; VREG spill slot 9
_vreg10:   .word 0     ; VREG spill slot 10
_vreg11:   .word 0     ; VREG spill slot 11
_vreg12:   .word 0     ; VREG spill slot 12
_vreg13:   .word 0     ; VREG spill slot 13
_vreg14:   .word 0     ; VREG spill slot 14
_vreg15:   .word 0     ; VREG spill slot 15

; Code section at 0x0100 (above stack area)
    .org 0x0100
_start:
    CALL _main
    HLT

    .global _factorial

    .text

; Function: factorial
_factorial:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 6 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 1
    STA _vreg0
    LDI 1
    STA _vreg1
    JMP _L3
_L2:
    LDA _vreg1
    TAX
    LDA _vreg0
    MUL
    STA _vreg0
    LDA _vreg1
    STA _tmp
    LDI 1
    ADD _tmp
    STA _vreg1
_L3:
    LDA _vreg1
    STA _tmp2
    LDA 4,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JLE _L2
    LDA _vreg0
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 5
    PUSH
    CALL _factorial
    STA _vreg0
; ret - value in AC
_L5:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
