; NEANDER-X 16-bit Assembly
; Generated by LCC (16-bit target)

; Runtime variables (page zero for fast access)
    .org 0x0000
_tmp:    .word 0     ; General purpose 16-bit temp
_tmp2:   .word 0     ; Second 16-bit temp for binary ops
_tmp_lo: .byte 0     ; 16-bit temp low byte
_tmp_hi: .byte 0     ; 16-bit temp high byte
_t2_lo:  .byte 0     ; Second 16-bit temp low
_t2_hi:  .byte 0     ; Second 16-bit temp high
_t3_lo:  .byte 0     ; Third 16-bit temp low (for 32-bit ops)
_t3_hi:  .byte 0     ; Third 16-bit temp high
_t4_lo:  .byte 0     ; Fourth 16-bit temp low (for 32-bit ops)
_t4_hi:  .byte 0     ; Fourth 16-bit temp high
_zero:   .byte 0     ; Constant zero (for clearing carry)

; Code section starts at 0x0100 (page 0 reserved for stack)
    .org 0x0100

    .global _to_upper

    .text

; Function: to_upper
_to_upper:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDA 4
    PUSH
    LDA 4+1
    STA 4
    LDA 4
    PUSH
    LDI 0
    LDI lo(97)
    PUSH
    LDI hi(97)
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    STA _t2_lo
    LDA _t2_hi
    CMP _tmp_hi
    JN _L2
    JNZ _nlt__L2
    LDA _t2_lo
    CMP _tmp_lo
    JC _L2
_nlt__L2:
    LDI lo(122)
    PUSH
    LDI hi(122)
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    STA _t2_lo
    LDA _tmp_hi
    CMP _t2_hi
    JN _L2
    JNZ _ngt__L2
    LDA _tmp_lo
    CMP _t2_lo
    JC _L2
_ngt__L2:
    LDA 4
    PUSH
    LDI 0
    LDI lo(32)
    PUSH
    LDI hi(32)
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    LDI 0
    ADD _zero
    LDA _t2_lo
    SUB _tmp_lo
    PUSH
    LDA _t2_hi
    SBC _tmp_hi
    PUSH
    LDI 0
    TAY
    POP
    JMP _L1
_L2:
    LDA 4
    PUSH
    LDI 0
    TAY
    POP
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 12 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 104
    STA -2
    LDI 105
    STA -4
    LDA -2
    PUSH
    LDI 0
    PUSH
    POP
    PUSH
    PUSH
    CALL _to_upper
    PUSH
    TYA
    STA -6
    LDA -4
    PUSH
    LDI 0
    PUSH
    POP
    PUSH
    PUSH
    CALL _to_upper
    PUSH
    TYA
    STA -8
    LDA -6
    PUSH
    LDI 0
    LDA -8
    PUSH
    LDI 0
    STA _tmp_lo
    POP
    STA _tmp_hi
    POP
    STA _t2_hi
    POP
    ADD _tmp_lo
    PUSH
    LDA _t2_hi
    ADC _tmp_hi
    TAY
    POP
_L4:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
