; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _divide

    .text

; Function: divide
_divide:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    LDA 6,FP
    TAX
    POP
    DIV
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _modulo

; Function: modulo
_modulo:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    LDA 6,FP
    TAX
    POP
    MOD
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 16 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 7
    PUSH
    LDI 100
    PUSH
    CALL _divide
    STA -10,FP
    STA -2,FP
    LDI 7
    PUSH
    LDI 100
    PUSH
    CALL _modulo
    STA -12,FP
    STA -4,FP
    LDI 10
    PUSH
    LDI 50
    PUSH
    CALL _divide
    STA -14,FP
    STA -6,FP
    LDI 5
    PUSH
    LDI 17
    PUSH
    CALL _modulo
    STA -16,FP
    STA -8,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
    STA _tmp
    LDA -8,FP
    ADD _tmp
; ret - value in AC
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
