; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _main

    .text

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    LDI 0
    STA _arr
    LDI 1
    STA _arr+2
    LDI 2
    STA _arr+4
    LDI 3
    STA _arr+6
    LDI 4
    STA _arr+8
    LDI 5
    STA _arr+10
    LDI 6
    STA _arr+12
    LDI 7
    STA _arr+14
    LDI 8
    STA _arr+16
    LDI 9
    STA _arr+18
    LDA _arr
    STA _tmp
    LDA _arr+2
    ADD _tmp
    STA _tmp
    LDA _arr+4
    ADD _tmp
    STA _tmp
    LDA _arr+6
    ADD _tmp
    STA _tmp
    LDA _arr+8
    ADD _tmp
    STA _tmp
    LDA _arr+10
    ADD _tmp
    STA _tmp
    LDA _arr+12
    ADD _tmp
    STA _tmp
    LDA _arr+14
    ADD _tmp
    STA _tmp
    LDA _arr+16
    ADD _tmp
    STA _tmp
    LDA _arr+18
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _arr
_arr:
    .space 20

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
