; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Memory layout:
; 0x0000-0x002F: Runtime variables (below stack area)
; 0x0030-0x00FF: Stack (SP starts at 0x00FF, grows down)
; 0x0100+: Code

; Jump to startup code at 0x0100
    .org 0x0000
    JMP _start

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values
_vreg0:   .word 0     ; VREG spill slot 0
_vreg1:   .word 0     ; VREG spill slot 1
_vreg2:   .word 0     ; VREG spill slot 2
_vreg3:   .word 0     ; VREG spill slot 3
_vreg4:   .word 0     ; VREG spill slot 4
_vreg5:   .word 0     ; VREG spill slot 5
_vreg6:   .word 0     ; VREG spill slot 6
_vreg7:   .word 0     ; VREG spill slot 7
_vreg8:   .word 0     ; VREG spill slot 8
_vreg9:   .word 0     ; VREG spill slot 9
_vreg10:   .word 0     ; VREG spill slot 10
_vreg11:   .word 0     ; VREG spill slot 11
_vreg12:   .word 0     ; VREG spill slot 12
_vreg13:   .word 0     ; VREG spill slot 13
_vreg14:   .word 0     ; VREG spill slot 14
_vreg15:   .word 0     ; VREG spill slot 15

; Code section at 0x0100 (above stack area)
    .org 0x0100
_start:
    CALL _main
    HLT

    .global _main

    .text

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    LDI 0
    STA _arr
    LDI 1
    STA _arr+2
    LDI 2
    STA _arr+4
    LDI 3
    STA _arr+6
    LDI 4
    STA _arr+8
    LDI 5
    STA _arr+10
    LDI 6
    STA _arr+12
    LDI 7
    STA _arr+14
    LDI 8
    STA _arr+16
    LDI 9
    STA _arr+18
    LDA _arr
    STA _tmp
    LDA _arr+2
    ADD _tmp
    STA _tmp
    LDA _arr+4
    ADD _tmp
    STA _tmp
    LDA _arr+6
    ADD _tmp
    STA _tmp
    LDA _arr+8
    ADD _tmp
    STA _tmp
    LDA _arr+10
    ADD _tmp
    STA _tmp
    LDA _arr+12
    ADD _tmp
    STA _tmp
    LDA _arr+14
    ADD _tmp
    STA _tmp
    LDA _arr+16
    ADD _tmp
    STA _tmp
    LDA _arr+18
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET

    .bss
    .global _arr
_arr:
    .space 20

; End of program
    HLT
