; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Memory layout:
; 0x0000-0x002F: Runtime variables (below stack area)
; 0x0030-0x00FF: Stack (SP starts at 0x00FF, grows down)
; 0x0100+: Code

; Jump to startup code at 0x0100
    .org 0x0000
    JMP _start

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values
_vreg0:   .word 0     ; VREG spill slot 0
_vreg1:   .word 0     ; VREG spill slot 1
_vreg2:   .word 0     ; VREG spill slot 2
_vreg3:   .word 0     ; VREG spill slot 3
_vreg4:   .word 0     ; VREG spill slot 4
_vreg5:   .word 0     ; VREG spill slot 5
_vreg6:   .word 0     ; VREG spill slot 6
_vreg7:   .word 0     ; VREG spill slot 7
_vreg8:   .word 0     ; VREG spill slot 8
_vreg9:   .word 0     ; VREG spill slot 9
_vreg10:   .word 0     ; VREG spill slot 10
_vreg11:   .word 0     ; VREG spill slot 11
_vreg12:   .word 0     ; VREG spill slot 12
_vreg13:   .word 0     ; VREG spill slot 13
_vreg14:   .word 0     ; VREG spill slot 14
_vreg15:   .word 0     ; VREG spill slot 15

; Code section at 0x0100 (above stack area)
    .org 0x0100
_start:
    CALL _main
    HLT

    .global _test_lt

    .text

; Function: test_lt
_test_lt:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGE _L2
    LDI 1
; ret - value in AC
    JMP _L1
_L2:
    LDI 0
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_gt

; Function: test_gt
_test_gt:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JLE _L5
    LDI 1
; ret - value in AC
    JMP _L4
_L5:
    LDI 0
; ret - value in AC
_L4:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_le

; Function: test_le
_test_le:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGT _L8
    LDI 1
; ret - value in AC
    JMP _L7
_L8:
    LDI 0
; ret - value in AC
_L7:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_ge

; Function: test_ge
_test_ge:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JN _L11
    LDI 1
; ret - value in AC
    JMP _L10
_L11:
    LDI 0
; ret - value in AC
_L10:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_eq

; Function: test_eq
_test_eq:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JNZ _L14
    LDI 1
; ret - value in AC
    JMP _L13
_L14:
    LDI 0
; ret - value in AC
_L13:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_ne

; Function: test_ne
_test_ne:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JZ _L17
    LDI 1
; ret - value in AC
    JMP _L16
_L17:
    LDI 0
; ret - value in AC
_L16:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 20 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    STA _vreg0
    LDI 10
    PUSH
    LDI 5
    PUSH
    CALL _test_lt
    STA _vreg1
    LDA _vreg0
    STA _tmp
    LDA _vreg1
    ADD _tmp
    STA _vreg0
    LDI 5
    PUSH
    LDI 10
    PUSH
    CALL _test_gt
    STA _vreg2
    LDA _vreg0
    STA _tmp
    LDA _vreg2
    ADD _tmp
    STA _vreg0
    LDI 5
    STA _vreg3
    LDA _vreg3
    PUSH
    LDA _vreg3
    PUSH
    CALL _test_le
    STA _vreg4
    LDA _vreg0
    STA _tmp
    LDA _vreg4
    ADD _tmp
    STA _vreg0
    LDI 10
    STA _vreg5
    LDA _vreg5
    PUSH
    LDA _vreg5
    PUSH
    CALL _test_ge
    STA _vreg6
    LDA _vreg0
    STA _tmp
    LDA _vreg6
    ADD _tmp
    STA _vreg0
    LDI 42
    STA _vreg7
    LDA _vreg7
    PUSH
    LDA _vreg7
    PUSH
    CALL _test_eq
    STA _vreg8
    LDA _vreg0
    STA _tmp
    LDA _vreg8
    ADD _tmp
    STA _vreg0
    LDI 2
    PUSH
    LDI 1
    PUSH
    CALL _test_ne
    STA _vreg9
    LDA _vreg0
    STA _tmp
    LDA _vreg9
    ADD _tmp
    STA _vreg0
    LDA _vreg0
; ret - value in AC
_L19:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
