; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _test_lt

    .text

; Function: test_lt
_test_lt:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGE _L2
    LDI 1
; ret - value in AC
    JMP _L1
_L2:
    LDI 0
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_gt

; Function: test_gt
_test_gt:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JLE _L5
    LDI 1
; ret - value in AC
    JMP _L4
_L5:
    LDI 0
; ret - value in AC
_L4:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_le

; Function: test_le
_test_le:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGT _L8
    LDI 1
; ret - value in AC
    JMP _L7
_L8:
    LDI 0
; ret - value in AC
_L7:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_ge

; Function: test_ge
_test_ge:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JN _L11
    LDI 1
; ret - value in AC
    JMP _L10
_L11:
    LDI 0
; ret - value in AC
_L10:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_eq

; Function: test_eq
_test_eq:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JNZ _L14
    LDI 1
; ret - value in AC
    JMP _L13
_L14:
    LDI 0
; ret - value in AC
_L13:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _test_ne

; Function: test_ne
_test_ne:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JZ _L17
    LDI 1
; ret - value in AC
    JMP _L16
_L17:
    LDI 0
; ret - value in AC
_L16:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 20 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    STA -2,FP
    LDI 10
    PUSH
    LDI 5
    PUSH
    CALL _test_lt
    STA -4,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA -2,FP
    LDI 5
    PUSH
    LDI 10
    PUSH
    CALL _test_gt
    STA -6,FP
    LDA -2,FP
    STA _tmp
    LDA -6,FP
    ADD _tmp
    STA -2,FP
    LDI 5
    STA -8,FP
    LDA -8,FP
    PUSH
    LDA -8,FP
    PUSH
    CALL _test_le
    STA -10,FP
    LDA -2,FP
    STA _tmp
    LDA -10,FP
    ADD _tmp
    STA -2,FP
    LDI 10
    STA -12,FP
    LDA -12,FP
    PUSH
    LDA -12,FP
    PUSH
    CALL _test_ge
    STA -14,FP
    LDA -2,FP
    STA _tmp
    LDA -14,FP
    ADD _tmp
    STA -2,FP
    LDI 42
    STA -16,FP
    LDA -16,FP
    PUSH
    LDA -16,FP
    PUSH
    CALL _test_eq
    STA -18,FP
    LDA -2,FP
    STA _tmp
    LDA -18,FP
    ADD _tmp
    STA -2,FP
    LDI 2
    PUSH
    LDI 1
    PUSH
    CALL _test_ne
    STA -20,FP
    LDA -2,FP
    STA _tmp
    LDA -20,FP
    ADD _tmp
    STA -2,FP
    LDA -2,FP
; ret - value in AC
_L19:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
