; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _add3

    .text

; Function: add3
_add3:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp
    LDA 6,FP
    ADD _tmp
    STA _tmp
    LDA 8,FP
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _add4

; Function: add4
_add4:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp
    LDA 6,FP
    ADD _tmp
    STA _tmp
    LDA 8,FP
    ADD _tmp
    STA _tmp
    LDA 10,FP
    ADD _tmp
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _add5

; Function: add5
_add5:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp
    LDA 6,FP
    ADD _tmp
    STA _tmp
    LDA 8,FP
    ADD _tmp
    STA _tmp
    LDA 10,FP
    ADD _tmp
    STA _tmp
    LDA 12,FP
    ADD _tmp
; ret - value in AC
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 14 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 30
    PUSH
    LDI 20
    PUSH
    LDI 10
    PUSH
    CALL _add3
    STA -8,FP
    STA -2,FP
    LDI 4
    PUSH
    LDI 3
    PUSH
    LDI 2
    PUSH
    LDI 1
    PUSH
    CALL _add4
    STA -10,FP
    STA -4,FP
    LDI 10
    STA -12,FP
    LDA -12,FP
    PUSH
    LDA -12,FP
    PUSH
    LDI 30
    PUSH
    LDI 20
    PUSH
    LDA -12,FP
    PUSH
    CALL _add5
    STA -14,FP
    STA -6,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
; ret - value in AC
_L4:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
