; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Memory layout:
; 0x0000-0x002F: Runtime variables (below stack area)
; 0x0030-0x00FF: Stack (SP starts at 0x00FF, grows down)
; 0x0100+: Code

; Jump to startup code at 0x0100
    .org 0x0000
    JMP _start

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values
_vreg0:   .word 0     ; VREG spill slot 0
_vreg1:   .word 0     ; VREG spill slot 1
_vreg2:   .word 0     ; VREG spill slot 2
_vreg3:   .word 0     ; VREG spill slot 3
_vreg4:   .word 0     ; VREG spill slot 4
_vreg5:   .word 0     ; VREG spill slot 5
_vreg6:   .word 0     ; VREG spill slot 6
_vreg7:   .word 0     ; VREG spill slot 7
_vreg8:   .word 0     ; VREG spill slot 8
_vreg9:   .word 0     ; VREG spill slot 9
_vreg10:   .word 0     ; VREG spill slot 10
_vreg11:   .word 0     ; VREG spill slot 11
_vreg12:   .word 0     ; VREG spill slot 12
_vreg13:   .word 0     ; VREG spill slot 13
_vreg14:   .word 0     ; VREG spill slot 14
_vreg15:   .word 0     ; VREG spill slot 15

; Code section at 0x0100 (above stack area)
    .org 0x0100
_start:
    CALL _main
    HLT

    .global _double_val

    .text

; Function: double_val
_double_val:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDA 4,FP
    STA _vreg0
    LDA _vreg0
    STA _tmp
    LDA _vreg0
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _add_ten

; Function: add_ten
_add_ten:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp
    LDI 10
    ADD _tmp
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 24 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 5
    PUSH
    CALL _double_val
    STA _vreg0
    PUSH
    CALL _double_val
    STA _vreg1
    PUSH
    CALL _add_ten
    STA _vreg2
    STA -2,FP
    LDI 5
    PUSH
    CALL _add_ten
    STA _vreg3
    PUSH
    CALL _double_val
    STA _vreg4
    PUSH
    CALL _double_val
    STA _vreg5
    STA -4,FP
    LDI 0
    PUSH
    CALL _add_ten
    STA _vreg6
    PUSH
    CALL _add_ten
    STA _vreg7
    PUSH
    CALL _add_ten
    STA _vreg8
    STA -6,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
; ret - value in AC
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
