; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _double_val

    .text

; Function: double_val
_double_val:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 2 bytes for locals
    LDI 0
    PUSH
    STA -2,FP
    LDA -2,FP
    STA _tmp
    LDA -2,FP
    ADD _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _add_ten

; Function: add_ten
_add_ten:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp
    LDI 10
    ADD _tmp
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 24 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 5
    PUSH
    CALL _double_val
    STA -8,FP
    PUSH
    CALL _double_val
    STA -10,FP
    PUSH
    CALL _add_ten
    STA -12,FP
    STA -2,FP
    LDI 5
    PUSH
    CALL _add_ten
    STA -14,FP
    PUSH
    CALL _double_val
    STA -16,FP
    PUSH
    CALL _double_val
    STA -18,FP
    STA -4,FP
    LDI 0
    PUSH
    CALL _add_ten
    STA -20,FP
    PUSH
    CALL _add_ten
    STA -22,FP
    PUSH
    CALL _add_ten
    STA -24,FP
    STA -6,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
; ret - value in AC
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
