; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Memory layout:
; 0x0000-0x002F: Runtime variables (below stack area)
; 0x0030-0x00FF: Stack (SP starts at 0x00FF, grows down)
; 0x0100+: Code

; Jump to startup code at 0x0100
    .org 0x0000
    JMP _start

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values
_vreg0:   .word 0     ; VREG spill slot 0
_vreg1:   .word 0     ; VREG spill slot 1
_vreg2:   .word 0     ; VREG spill slot 2
_vreg3:   .word 0     ; VREG spill slot 3
_vreg4:   .word 0     ; VREG spill slot 4
_vreg5:   .word 0     ; VREG spill slot 5
_vreg6:   .word 0     ; VREG spill slot 6
_vreg7:   .word 0     ; VREG spill slot 7
_vreg8:   .word 0     ; VREG spill slot 8
_vreg9:   .word 0     ; VREG spill slot 9
_vreg10:   .word 0     ; VREG spill slot 10
_vreg11:   .word 0     ; VREG spill slot 11
_vreg12:   .word 0     ; VREG spill slot 12
_vreg13:   .word 0     ; VREG spill slot 13
_vreg14:   .word 0     ; VREG spill slot 14
_vreg15:   .word 0     ; VREG spill slot 15

; Code section at 0x0100 (above stack area)
    .org 0x0100
_start:
    CALL _main
    HLT

    .global _classify

    .text

; Function: classify
_classify:
    ; Prologue
    PUSH_FP
    TSF
    LDI 0
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGE _L2
    LDI 1
; ret - value in AC
    JMP _L1
_L2:
    LDI 0
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JNZ _L4
    LDI 2
; ret - value in AC
    JMP _L1
_L4:
    LDI 10
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGE _L6
    LDI 3
; ret - value in AC
    JMP _L1
_L6:
    LDI 100
    STA _tmp
    LDA 4,FP
    CMP _tmp
    JGE _L8
    LDI 4
; ret - value in AC
    JMP _L1
_L8:
    LDI 5
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _max3

; Function: max3
_max3:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 4 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDA 4,FP
    LDA 4,FP
    STA _vreg0
    LDA _vreg0
    STA _tmp2
    LDA 6,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L11
    LDA _vreg0
    STA _tmp2
    LDA 8,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L11
    LDA 4,FP
; ret - value in AC
    JMP _L10
_L11:
    LDA 6,FP
    LDA 6,FP
    STA _vreg1
    LDA _vreg1
    STA _tmp2
    LDA 4,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L13
    LDA _vreg1
    STA _tmp2
    LDA 8,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L13
    LDA 6,FP
; ret - value in AC
    JMP _L10
_L13:
    LDA 8,FP
; ret - value in AC
_L10:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 34 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI -5
    PUSH
    CALL _classify
    STA _vreg0
    STA -2,FP
    LDI 0
    PUSH
    CALL _classify
    STA _vreg1
    STA -4,FP
    LDI 5
    PUSH
    CALL _classify
    STA _vreg2
    STA -6,FP
    LDI 50
    PUSH
    CALL _classify
    STA _vreg3
    STA -8,FP
    LDI 200
    PUSH
    CALL _classify
    STA _vreg4
    STA -10,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
    STA _tmp
    LDA -8,FP
    ADD _tmp
    STA _tmp
    LDA -10,FP
    ADD _tmp
    STA -12,FP
    LDI 15
    PUSH
    LDI 20
    PUSH
    LDI 10
    PUSH
    CALL _max3
    STA _vreg5
    STA -14,FP
    LDI 25
    PUSH
    LDI 5
    PUSH
    LDI 30
    PUSH
    CALL _max3
    STA _vreg6
    STA -16,FP
    LDI 35
    PUSH
    LDI 2
    PUSH
    LDI 1
    PUSH
    CALL _max3
    STA _vreg7
    STA -18,FP
    LDA -12,FP
    STA _tmp
    LDA -14,FP
    ADD _tmp
    STA _tmp
    LDA -16,FP
    ADD _tmp
    STA _tmp
    LDA -18,FP
    ADD _tmp
; ret - value in AC
_L15:
    ; Epilogue
    TFS
    POP_FP
    RET

; End of program
    HLT
