; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _classify

    .text

; Function: classify
_classify:
    ; Prologue
    PUSH_FP
    TSF
    LDA 4,FP
    STA _tmp2
    LDI 0
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JGE _L2
    LDI 1
; ret - value in AC
    JMP _L1
_L2:
    LDA 4,FP
    LDI 0
    STA _tmp
    POP
    CMP _tmp
    JNZ _L4
    LDI 2
; ret - value in AC
    JMP _L1
_L4:
    LDA 4,FP
    STA _tmp2
    LDI 10
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JGE _L6
    LDI 3
; ret - value in AC
    JMP _L1
_L6:
    LDA 4,FP
    STA _tmp2
    LDI 100
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JGE _L8
    LDI 4
; ret - value in AC
    JMP _L1
_L8:
    LDI 5
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _max3

; Function: max3
_max3:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 4 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDA 4,FP
    STA -2,FP
    LDA -2,FP
    STA _tmp2
    LDA 6,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L11
    LDA -2,FP
    STA _tmp2
    LDA 8,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L11
    LDA 4,FP
; ret - value in AC
    JMP _L10
_L11:
    LDA 6,FP
    STA -4,FP
    LDA -4,FP
    STA _tmp2
    LDA 4,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L13
    LDA -4,FP
    STA _tmp2
    LDA 8,FP
    STA _tmp
    LDA _tmp2
    CMP _tmp
    JN _L13
    LDA 6,FP
; ret - value in AC
    JMP _L10
_L13:
    LDA 8,FP
; ret - value in AC
_L10:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 34 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI -5
    PUSH
    CALL _classify
    STA -20,FP
    STA -2,FP
    LDI 0
    PUSH
    CALL _classify
    STA -22,FP
    STA -4,FP
    LDI 5
    PUSH
    CALL _classify
    STA -24,FP
    STA -6,FP
    LDI 50
    PUSH
    CALL _classify
    STA -26,FP
    STA -8,FP
    LDI 200
    PUSH
    CALL _classify
    STA -28,FP
    STA -10,FP
    LDA -2,FP
    STA _tmp
    LDA -4,FP
    ADD _tmp
    STA _tmp
    LDA -6,FP
    ADD _tmp
    STA _tmp
    LDA -8,FP
    ADD _tmp
    STA _tmp
    LDA -10,FP
    ADD _tmp
    STA -12,FP
    LDI 15
    PUSH
    LDI 20
    PUSH
    LDI 10
    PUSH
    CALL _max3
    STA -30,FP
    STA -14,FP
    LDI 25
    PUSH
    LDI 5
    PUSH
    LDI 30
    PUSH
    CALL _max3
    STA -32,FP
    STA -16,FP
    LDI 35
    PUSH
    LDI 2
    PUSH
    LDI 1
    PUSH
    CALL _max3
    STA -34,FP
    STA -18,FP
    LDA -12,FP
    STA _tmp
    LDA -14,FP
    ADD _tmp
    STA _tmp
    LDA -16,FP
    ADD _tmp
    STA _tmp
    LDA -18,FP
    ADD _tmp
; ret - value in AC
_L15:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
