; NEANDER-X 16-bit Assembly
; Generated by LCC (native 16-bit target)

; Code starts at 0x0000
    .org 0x0000

    .global _and_op

    .text

; Function: and_op
_and_op:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    AND _tmp
; ret - value in AC
_L1:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _or_op

; Function: or_op
_or_op:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    OR _tmp
; ret - value in AC
_L2:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _xor_op

; Function: xor_op
_xor_op:
    ; Prologue
    PUSH_FP
    TSF
    LDA 6,FP
    STA _tmp
    LDA 4,FP
    XOR _tmp
; ret - value in AC
_L3:
    ; Epilogue
    TFS
    POP_FP
    RET
    .global _main

; Function: main
_main:
    ; Prologue
    PUSH_FP
    TSF
    ; Allocate 16 bytes for locals
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 0
    PUSH
    LDI 255
    STA -2,FP
    LDI 3855
    STA -4,FP
    LDA -4,FP
    PUSH
    LDA -2,FP
    PUSH
    CALL _and_op
    STA -12,FP
    STA -6,FP
    LDA -4,FP
    PUSH
    LDA -2,FP
    PUSH
    CALL _or_op
    STA -14,FP
    STA -8,FP
    LDA -4,FP
    PUSH
    LDA -2,FP
    PUSH
    CALL _xor_op
    STA -16,FP
    STA -10,FP
    LDA -6,FP
    STA _tmp
    LDA -8,FP
    ADD _tmp
    STA _tmp
    LDA -10,FP
    ADD _tmp
; ret - value in AC
_L4:
    ; Epilogue
    TFS
    POP_FP
    RET

; Runtime variables
_tmp:     .word 0     ; General purpose 16-bit temp
_tmp_hi:  .word 0     ; For 32-bit ops (high word)
_tmp2:    .word 0     ; Second 16-bit temp
_tmp2_hi: .word 0     ; For 32-bit ops (high word)
_mask_ff: .word 0x00FF ; Mask for 8-bit values

; End of program
    HLT
